### ISSUE TITLE
Additional example for <dc:title>

### ISSUE THREAD

**Issue by emuller-amazon** [w3c/epub-specs#1527] opened 2021-02-25 17:24 UTC
https://www.w3.org/TR/2021/WD-epub-33-20210224/#sec-opf-dctitle

Example 7 suggest that multiple <dc:title> elements form collectively "the" title. But there is no discussion of the meaning of multiple <dc:title> elements **with different xml:lang**. 

My understanding is that representing the title in different languages is done via the alternate-script property:

<dc:title xml:lang='fr' id='title'>Les fleurs du mal</dc:title>
<meta refines='#title' property='alternate-script' xml:lang='en'>Flowers of Evil</meta>

and not by:

<dc:title xml:lang='fr'>Les fleurs du mal</dc:title>
<dc:title xml:lang='en'>Flowers of Evil</dc:title>

I think it would be worth including the first form as an example in this section, introduced by something like "Titles in alternate languages are represented by <meta> elements, rather than multiple <dc:title> elements with different xml:lang. [EXAMPLE]".

**Comment by iherman** [comment] 2021-02-26 09:45
I am not sure. 

I agree it is not properly specified, and it should. 

However, there is a rule in the [section on language element](https://www.w3.org/TR/2021/WD-epub-33-20210224/#sec-opf-dclanguage):

> Although additional language elements MAY be specified for multilingual Publications, the first language element in document order is considered the primary language of the EPUB Publication.

I think consistency would require to consider the same approach for the usage of `xml:lang`. I.e., this would be valid:

> <dc:title xml:lang='fr'>Les fleurs du mal</dc:title>
> <dc:title xml:lang='en'>Flowers of Evil</dc:title>

and the French title would be the “primary”. In other words, having such repeated entries should not be considered as an error (whereas that would be the consequence of what you propose). Actually, I would think that this should be a general rule, not specifically on titles, i.e., should be specified on the [section on `xml:lang`](https://www.w3.org/TR/2021/WD-epub-33-20210224/#sec-shared-attrs).

I realize that the `alternate-script` is also a valid option and I am not sure how to differentiate the two approaches. I “feel” the approach between a translation of a term (which is the case of the title example) and information on and alternate script (like the [alternate script usage example](https://www.w3.org/TR/2021/WD-epub-33-20210224/#example-10)). The latter is not a _translation_ of Murakami's name, but using a different script to express the same information.

**Comment by llemeurfr** [comment] 2021-02-26 12:48
The practical use of multiple titles in multiple language is not 100% clear, and the expected behavior of reading systems neither. 

In exemple 7, multiple titles are only used to display "segmented" titles. It is not clearly expressed if a reading system should display the segments on multiple lines, but I suppose this is the intended display: this should certainly be specified.  

From this example, we can infer that multiple titles are NOT intended to provide alternative titles, and especially not the original title of a translated book. If there was such a use case, stronger semantics would be useful (something like "translationOfWork" in schema-org). 

Therefore adding xml:lang to a dc:title is a way to indicate the language of a segment of a full title (for proper TTS maybe) and does not mean anything else. 

One could find: 
<dc:title xml:lang='en'>Harry Potter</dc:title>
<dc:title xml:lang='fr'>à l'école des sorciers</dc:title>

**Comment by mattgarrish** [comment] 2021-02-26 21:06
> Therefore adding xml:lang to a dc:title is a way to indicate the language of a segment of a full title (for proper TTS maybe) and does not mean anything else.

Yes, fully agree with this.

There's no specific association between the elements and their use of xml:lang. That's where alternate-script differs in that you use the `refines` attribute to create a linked set of alternatives.

**Comment by iherman** [comment] 2021-02-27 08:29
> There's no specific association between the elements and their use of xml:lang. That's where alternate-script differs in that you use the `refines` attribute to create a linked set of alternatives.

Ok, I am convinced. But this means, looking at the original question raised by @emuller-amazon:

> But there is no discussion of the meaning of multiple dc:title elements with different xml:lang.

the answer is that the document assigns no particular meaning to the order, i.e., order is irrelevant. If we agree with this, then it is worth making it clear in the spec. (Not only for the title element, but to all elements that use `xml:lang`.)

**Comment by llemeurfr** [comment] 2021-02-28 10:56
@iherman, your proposal of agreeing that metadata order is not relevant is causing an issue: the EPUB 3.3 spec states that "The first title element in document order is the main title of the EPUB Publication (i.e., the primary one Reading Systems present to users).".  The EPUB 3 Reading Systems specs adds: "Reading Systems MUST recognize the first title element in document order as the main title of the EPUB Publication and present it to users before other title elements. 

I 100% agree that in general, metadata order SHOULD NOT matter. But the EPUB 3 spec has taken a strange route so far about this aspect. I believe that originally multiple titles were meant to be specialized via meta/@refine elements: this is what we find e.g. in http://bid.ub.edu/en/35/centelles.htm section 5.2. But refine being out of court since then, the notion was "simplified" as a notion of "multi-part" titles, which makes no sense at a Dublin Core level. 

Therefore we have different possible routes:
1/ come back to the original notion of specialized titles (via refine)
2/ keep this awkward "multipart title" with a meaningful order, very specific to EPUB 3, and assume critiques. 
3/ re-define multiple titles as translations of the title of the book (and deprecate the use  of the more complex alternate-script).

Note: we find the same kind of issue in W3C Audiobooks and more generically Web publications: name can be multiple but there is no spec relative to how user agents must handle multiple names.

**Comment by mattgarrish** [comment] 2021-02-28 12:06
> I 100% agree that in general, metadata order SHOULD NOT matter.

But then how are you going to order authors? There's no simple solution that's going to work everywhere.

This is the problem of having used dublin core metadata in the first place - the lack of any meaningful information about what the tags represent. Adding refines was supposed to try and patch that hole, but reading systems don't use it. That information can still be attached, but it's complex and unused.

That's why the ordering requirements were added a couple of revisions ago - because there was no consistency in how the metadata was being interpreted/prioritized.

> re-define multiple titles as translations of the title of the book (and deprecate the use of the more complex alternate-script).

But won't that lead to:

```
<dc:creator>Matt Garrish</dc:creator>
<dc:creator xml:lang="fr">Laurent Lemeur</dc:creator>
```

making you a translation of my name in French, instead of `xml:lang` defining how to properly pronounce your name?

I don't see the situation improving for titles, either. If a book has more than one subtitle, how do you determine which "translation" belongs to which segment?

If we need translations, as @iherman opened a question earlier in this revision, the most likely path would be to introduce another property along with `alternate-script` that can be used to associate the translations with the element they belong to.

I'm just not sure how important that metadata is. My understanding from past debates is that publishers don't generally put translations into the metadata. The publication will typically contain the metadata that is relevant to the region or language that it is being published into. If translations are needed for another region, the translated metadata is provided.

But if it clarifies how to do translations, then I'm not going to object to something like a `translation` property. I'm just not terribly convinced it will get used any better than any of the others we've created.

**Comment by llemeurfr** [comment] 2021-02-28 18:42
> If we need translations, 

Using multiple titles for translations (I called it 3/) is far from being my favorite indeed, as I totally agree with everything we've said before against it.  

> Adding refines was supposed to try and patch that hole, but reading systems don't use it. 

Reading systems have not implemented refine mainly because its use was under-specified: refine values are too generic; one individual author can do too many thing with it. 

I would in fact be in favour of specifying that multiple titles should only be used along with "refine" (I called it 1/), add examples using the existing set of refines values (based on https://www.w3.org/publishing/epub3/epub-packages.html#sec-title-type), and specify that a refine value should be unique to a title instance (not two titles with the same refine value). I'm for instance ready to push the adoption of a "subtitle" refine value in Readium software and get this handled by its internal object representation of a publication. 

A sentence like "This specification does not define how to process additional title elements" (EPUB 3.3 Reading Systems) is the best way to make sure that reading systems won't process anything but one title (the first one being the best solution in such a case). Let's make it more interoperable.

**Comment by mattgarrish** [comment] 2021-02-28 21:20
> I would in fact be in favour of specifying that multiple titles should only be used along with "refine"

This is what we specified pre-EPUB 3.1, but it still depends either on `display-seq` or dom order (since a design principle of 3.0 was that reading systems not have to depend on interpreting `refines`):

> Every metadata section must include at least one title element containing the title for the EPUB Publication. Multiple title elements are permitted, but the title-type property should be attached to indicate the type of title (e.g., the main title of a work or a subtitle).
>
> ...
>
> When adding the title-type property, Authors should designate only one title element as containing the main title for the Publication. If no means of determining title types is provided, or understood, Reading Systems must treat the first title element in document order as the main title. This specification does not define how additional title elements should be processed in such situations.
> 
> The optional display-seq property may also be attached to each title to indicate their primacy for display and other rendering purposes.

See the examples here: http://idpf.org/epub/301/spec/epub-publications.html#sec-opf-dctitle

You can still do that now, as we [undeprecated `display-seq`](https://github.com/w3c/epub-specs/issues/1242) for 3.2.

> is the best way to make sure that reading systems won't process anything but one title

I think that's the tacit acknowledgement of the change. From what I remember of the discussions, it was common to put the full title in one element because that's the only way to ensure it gets rendered. The same was being done for authors, too.

I'm sceptical that reverting the spec prose will materially change that fact, as it wasn't authoring the metadata that was the problem. But we also have around a five year gap now where we've not been enforcing refines on titles to consider, too.

**Comment by iherman** [comment] 2021-03-01 10:59
I guess we are bound by the fact that we are supposed to be backward compatible. It may be true that the metadata is not widely used out there, but we actually do not really have data that would allow us to introduce backward incompatible changes. That also means that the order of metadata items does count.

I see two parallel routes coming to the fore from the discussion

- Following the proposal of @llemeurfr we add the sentence "This specification does not define how to process additional title elements" in the RS systems document (and also add something like that into the content). That is the acknowledgement of the situation we have now, and is also regardless of the existence (or not) of the `xml:lang` attribute. That also means that the answer to the original question of @emuller-amazon is that no specific behavior is defined; authors should avoid doing this, although it is not necessarily an error.
- introduce a separate 'translation' value for the refine mechanism. (Formally, we should have a separate issue for this.)

Is this a way to properly close this issue?

**Comment by llemeurfr** [comment] 2021-03-01 11:50
I didn't express myself clearly enough, sorry for that. My take is that the current situation is bad for interoperability and we should do better. For me, the sentence  "This specification does not define how to process additional title elements" represents a failure in the spec. Authors don't know they should generate one title only, because the spec lets them believe multiple titles are possible. But RS developers face so much uncertainty (= complexity) about what can be found there that they implement the simplest solution = pick one title (the first), forget others. 

As EPUB 3.3 is compatible with EPUB 3.0x, a solution which uses "refines" to make titles sort of unique (semantically speaking) is acceptable: we should therefore create a sample highlighting this solution.
 
On the opposite, the use and processing of "multipart" titles is not specified properly and only appears in example 7. An example should not take the place of a specification: we should therefore suppress this sample. 

In the RS specification, we should also replace the sentence  "This specification does not define ..." by a more detailed process, like "If multiple titles appear, the RS MUST process the first one in document order. RS MAY use `refines` properties to process semantic inflexions in subsequent title instances and show the corresponding labels to the users". 

Re. translations, I'm fine with the use of `alternate-script` and I won't push toward discussing a `translationOf` property. Adding also a sample highlighting the use of `alternate-script` would certainly answer to the question raised by @emuller-amazon.

**Comment by iherman** [comment] 2021-03-01 13:58
On the last item: I believe `alternate-script` is a misnomer for a translation (but I would welcome the comment on @r12a on this).

In the example:

```
<dc:title xml:lang='fr'>Les fleurs du mal</dc:title>
<dc:title xml:lang='en'>Flowers of Evil</dc:title>
```

the "Flower of Evil" does not represent an alternate script; it represents an alternate language (or translation). On the other hand, the example from the spec:

```
<dc:creator id="creator">Haruki Murakami</dc:creator>
<meta refines="#creator" property="alternate-script" xml:lang="ja">村上 春樹</meta>
```

represents (indeed) an alternate script for Murakami's name, it is not the translation of the name.

There are languages (e.g., Azeri) that have two different, but equally valid 'scripts' (Cyrillic and Arabic). The same terms in two different scripts would definitely not be considered as translations.

I do not know whether it is important to have a translation value for refines but, if conceptually we need it, it should be separated from alternate scripts.

**Comment by mattgarrish** [comment] 2021-03-02 17:05
> I believe `alternate-script` is a misnomer for a translation

Yes, but I believe it was meant to fill that role.

Interestingly, the description of `alternate-script` in the creator element doesn't make a distinction on its use (emphasis mine):

"The ... alternate-script property can be used to represent a creator's name in another language __or__ script."

That differs from the vocabulary definition:

"The alternate-script property provides an alternate expression of the associated property value in a language __and__ script identified by the xml:lang attribute."

In cases like this, the spec prose is more authoritative.

**Comment by iherman** [comment] 2021-03-03 11:21
Thinking through this again... what really strikes me is @llemeurfr's example:

```
<dc:title xml:lang='en'>Harry Potter</dc:title>
<dc:title xml:lang='fr'>à l'école des sorciers</dc:title>
```

which may, actually, be a good example why multipart titles are useful (although not terribly widespread). This is mostly due to the fact that `<dc:title>` has a pure string value; this solution is a poor man's solution to what a `<span>` would do. Which means that multiple titles, used in document order may have to be kept after all.

Going down this direction would mean:

(1) The [text on the title element](https://w3c.github.io/epub-specs/epub33/core/#sec-opf-dctitle) would be modified. It currently says

> The first title element in document order is the main title of the EPUB Publication (i.e., the primary one Reading Systems present to users). 

it should rather say something like 

> Several title elements _SHOULD_ be, conceptually, concatenated in document order, keeping the language and base directional information for each segment.

There may be an issue with backward compatibility, though, so the _SHOULD_ could be weakened by a _MAY_.

(2) Example 7, which is not particularly useful as it stands, should be exchanged to @llemeurfr's above, noting that the different language tags allow a better read-aloud in reading systems.

(3) The [handling of the title element in RS](https://w3c.github.io/epub-specs/epub33/rs/#metadata) should be modified along the same lines. We can also add the sentence on semantic inflection proposed above, but that is, sort of, orthogonal to the original discussion.

(I would raise a separate issue on whether a `translation` property is necessary.)

**Comment by mattgarrish** [comment] 2021-03-03 12:16
There are a couple of problems we're not touching on yet that have kept us out of how to handle multiple titles in the past, though. One, there isn't a requirement to use all the parts because it's simply not possible in all displays.

I don't think we should change that the first title is the primary if we can't expect concatenation (which we can't). If you drop that, we're back to where reading systems are justified in selecting any segment.

The other is what it means to "concatenate" the titles. Again, display constraints are going to play a factor in this, so whether that means adding lines between them, some kind of separator character, or just space is going to vary from RS to RS. Is it okay to use a couple of pieces? Do you have to indicate with an ellipsis that parts have been elided? Publishers tend to not like the result when this is left to reading systems.

And even if you try to avoid the reading system making any interpretations and put the full title in one element, it likely still gets truncated.

That's why it's hard to craft requirements for display that are realistic to get consistently supported.

**Comment by iherman** [comment] 2021-03-03 12:26
Sigh... why are you always right, @mattgarrish? :-)

But then, I would agree that example 7 in the spec does more harm than good, because it suggests a feature which isn't defined. And the spec remains silent as for what happens with several title elements. Which is pretty much the failure of the spec, as @llemeurfr said in https://github.com/w3c/epub-specs/issues/1527#issuecomment-787888600

(We can add the sentences on refine that @llemeurfr proposed in https://github.com/w3c/epub-specs/issues/1527#issuecomment-787888600, but I think that is a bit orthogonal to the original issue.)

**Comment by mattgarrish** [comment] 2021-03-03 14:52
> Which is pretty much the failure of the spec

Well, only in the sense that without being able to control how the information is used our hands are tied. It's the impossibility of wanting control over display while recognizing this is only metadata for reading systems to use as they prefer. (Other specs, like Audiobooks, aren't completely immune from these problems, either.)

I'd like to hear from more publishers on this topic before we consider changes, though.

- Do they add multipart titles or is it a dead feature?
- What do they do with multilingual titles? Does it come up?
- Do they include translations and have they been using alternate-script to do it?

We really need some more data on this. Jumping back on refines ignores the problems it didn't solve.

**Comment by mattgarrish** [comment] 2021-03-03 16:39
Interestingly, the dublin core folks recommend using dcterms:alternative for the secondary parts of multipart title. That would allow translations using xml:lang on both: https://www.dublincore.org/resources/userguide/creating_metadata/#Titles

The guidance is a bit too late, though.

**Comment by iherman** [comment] 2021-03-05 10:17
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-03-04-epub#section5) on 2021-03-04

List of resolutions:

- ***[Resolution No. 5](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-03-04-epub#resolution5):  Close issues 1527 and 1553, add editorial note regarding the current use of `dc:title` on the market and edit the example***

<details><summary><i>View the transcript</i></summary>

### 5. Handling of `dc:title` 

_See github issue [#1527](https://github.com/w3c/epub-specs/issues/1527), [#1553](https://github.com/w3c/epub-specs/issues/1553)._




**Wendy Reid:** these next two are related  
… there was some confusion about the example provided for `<dc:title>`  
… specifically when there are multiple, but they have different `xml:lang`-s  
… the discussion raised the question of whether refines needs a translation value  
… because the different titles might not be translations of one another  

**Dave Cramer:** is there any RS that does anything with the title beyond the bare minimum?  

**Wendy Reid:** probably no  

**Dave Cramer:** i've been writing tests and most RS seem to just display the first of each when there are fields that can occur multiple times  
… authors are asking for more expressive power, but no RS seems to be presenting this additional data to the user  

**Matt Garrish:** we tried what Laurent brought up in the issue  
… up to epub 3.1 you had to define your title type  
… and nobody used it, so we took it out  
… we'd be going back in circles. I think maybe we should just move on.  
… about the refines translation, we haven't found a case for it  
… people aren't making one epub with metadata in all these different various languages  

**Brady Duga:** agreed to all of that  
… unclear what an RS should even do when presented with the title in multiple different languages  

**Wendy Reid:** especially if the book itself is only in one language  
… one of the concerns we had was about JP, because Japanese has 3 different script sets, for lack of a better way of explaining it  
… so could an RS potentially implement a feature where the user could swap between script sets?  

**Dave Cramer:** ultimately the purpose of title is so you can distinguish books within your own collection  
… not meant to be as rigorous as a metadata record at some high level aggregator level (e.g. library of congress)  
… maybe change not needed  

**Brady Duga:** should we clarify the example then?  

**Matt Garrish:** we can't get rid of multipart `dc:titles` at this point  
… so do we guide people towards putting everything in a single title?  

**Dave Cramer:** I think our examples should reflect what will work for most people  
… so maybe we need to dial back the example  

**Matt Garrish:** or say that you can do multipart titles, but that there is no guarantee that RS can use them, or guarantee as to consistency  

**Brady Duga:** say "you can put multipart titles, but nobody knows what will happen, so you should probably only put one"  

> **Proposed resolution: Close issues 1527 and 1553, add editorial note regarding the current use of `dc:title` in the market** *(Wendy Reid)*

**Wendy Reid:** this should probably be an editorial note  

> **Proposed resolution: Close issues 1527 and 1553, add editorial note regarding the current use of `dc:title` on the market and edit the example** *(Wendy Reid)*

> *Brady Duga:* +1

> *Matthew Chan:* +1

> *Matt Garrish:* +!

> *Wendy Reid:* +1

> *Toshiaki Koike:* +1

> *Matt Garrish:* +1

> *Masakazu Kitahara:* +1

> ***Resolution #5: Close issues 1527 and 1553, add editorial note regarding the current use of `dc:title` on the market and edit the example***

</details>

**Comment by iherman** [comment] 2021-03-05 10:22
@mattgarrish I think there is some editorial work to be done on this, but I would prefer you do it, because I was not on the call...

**Closed as completed** 2021-03-19 12:25 UTC
Labels: Spec-EPUB3, EPUB33
