### ISSUE TITLE
Consider endnote(s) alternative for rearnote(s) in SSV

### ISSUE THREAD

**Issue by GoogleCodeExporter** [w3c/epub-specs#492] opened 2015-03-24 14:08 UTC
```
English speakers know endnotes as endnotes. Rearnote isn't a term people are 
familiar with, and initially causes confusion. It would be good to deprecate 
rearnote, if possible.
```

Original issue reported on code.google.com by `mgarrish` on 22 Jan 2015 at 7:56

**Comment by mattgarrish** [comment] 2016-04-25 16:58
Note that WAI-ARIA Publishing Module uses endnote/endnotes.

**Comment by mattgarrish** [comment] 2016-05-03 15:34
Closing as duplicate of #717

**Closed as completed by mattgarrish** 2016-05-03 15:34 UTC
Labels: Type-FeatureRequest, EPUB32
