### ISSUE TITLE
Non-ASCII characters in file names: general purpose bit 11 of ZIP

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#1027] opened 2018-04-16 23:53 UTC
Explicitly state that the general purpose bit 11 of ZIP shall be set, if ZIP item names use Unicode characters beyond US-ASCII.  More about this, see APPENDIX D - Language Encoding (EFS) in the ZIP spec.

**Comment by dauwhe** [comment] 2018-04-17 15:38
Current spec references Zip 6.3.3, but there is now a [Zip 6.3.4](https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT)

Would we add text to [section 4.2](http://w3c.github.io/publ-epub-revision/epub32/spec/epub-ocf.html#sec-zip-container-zipreqs) on Zip File Requirements?

Have there been any problems created by not stating this in the OCF spec? Will we expect epubcheck to validate this? Do zip tools do this automatically when confronted by UTF-8 filenames? Is it possible to create a compliant zip archive using commonly available tools?

**Comment by mattgarrish** [comment] 2018-04-18 15:00
> Current spec references Zip 6.3.3, but there is now a Zip 6.3.4

See https://github.com/w3c/publ-epub-revision/issues/964

**Comment by murata2makoto** [comment] 2018-05-03 14:33
Appnote allows two mechanisms for UTF-8.  One is from InfoZIP "Extra Field" values for UTF-8 file name".  The other is the general purpose bit 11.  I think that we should cleary recommend the latter.

**Comment by dauwhe** [comment] 2018-06-12 16:39
We have updated the references to point to Zip 6.3.4. I still have not seen any examples of any problems caused by EPUB not repeating something that's already in the zip spec. I propose that we close this issue.

**Comment by dauwhe** [comment] 2018-06-14 17:56
Consensus on the CG call today was that we don't need to explicitly call out this requirement of ZIP in our spec. We have no evidence of problems.

**Closed as completed by dauwhe** 2018-06-14 17:56 UTC
Labels: EPUB32
