### ISSUE TITLE
Definition of superseded

### ISSUE THREAD

**Issue by dauwhe** [w3c/epub-specs#1025] opened 2018-04-12 15:52 UTC
Our definition of superseded says,

> Reading Systems MUST NOT support the superseded feature in content that conforms to the current version of the specification.

This makes sense for things like ncx > nav and guide > landmarks. But what about something like bindings? Say we supercede epub:bindings in 3.2. What is a reading system's obligation when faced with a video element with bindings but native controls off?

And note we can now have content that is simultaneously valid 3.0, 3.0.1, and 3.2.

**Comment by GarthConboy** [comment] 2018-04-12 19:10
We likely need a "deprecated and RS's may not support it" (not "must not support it") -- per the likes of "Reintroduce the <bindings> element of <package>, but note that it is obsolete and deprecated.  Allow EPUB 3.2 Reading Systems to not support it." -- I'd think whatever we come up with should work for  binding, guide, NCX.

**Comment by dauwhe** [comment] 2018-04-13 14:39
How about an "obsolete"  or "legacy" category... name to be bikeshedded later:

1. Use by authors is "strongly discouraged"
2. Reading system support is optional. By the way, do we have spec language on how reading systems should respond to unknown elements in package? At least HTML and CSS are clear on how to parse unknown content. 
3. Validation tools should warn when these features are used (likely controversial because of how EpubCheck is used in practice, but I think authors must be notified if support for a feature is optional).
4. Such features will be removed in EPUB 4.X

**Comment by GarthConboy** [comment] 2018-04-13 17:38
I like it.  Matt?

I'd tend to leave off #4, as at least some of the these features are already clearly not OWP/EPUB4 compatible.

Perhaps "#4.  May be removed in a future version" or "#4. Marked for future removal" (which is close to something we've used before).

**Comment by murata2makoto** [comment] 2018-04-15 05:37
Very many features in EPUB 3 may be removed in EPUB 4.X.  If we mark only some features as "Marked for future removal", we implicitly say that other features will not be removed and send an incorrect message to users.

After all, EPUB 3.2 RSs will be used for existing EPUB 3 publications.  I think that any wording for controlling RS implementers will be ignored.

**Comment by mattgarrish** [comment] 2018-04-15 12:35
I oddly tend to side with Makoto on this one.

The only reason we introduced "marked for removal" was to really wag our finger at people that even though certain superseded features might have survived 3.1 (NCX only?) we were really, really going to toast them later. Sort of an early warning.

But predicting the future through specifications is a bad idea. What if the publishing working group decides for continued ease of translation they'll persist mechanisms to retain certain features, like the NCX? This group can't make decisions that are binding on another major revision.

The actual number of things we supersede is pretty small, though, and I just can't see us introducing new replacements anymore. We should deprecate everything that isn't purely a legacy EPUB 2 holdover. I wouldn't really call native controls a replacement for triggers, for example, as they don't allow custom interfaces to be built. If you want to build interfaces, accept that they have to be scripted.

Can we try reducing the categories to plain old deprecated and superseded and just tweak the definitions as follow:

>If a feature is marked as deprecated, the following hold true:
>
> - <strike>The feature will be removed in a future version of the specification. The feature is marked as deprecated in order to give Authors and EPUB Reading System developers time to prepare for removal.</strike>
>
> - It is strongly RECOMMENDED that Authors discontinue use of the feature in their EPUB Publications.
> 
> - Reading Systems <strike>MUST</strike> SHOULD continue to support the feature as it is defined<strike> until it is formally removed</strike>.
> 
> - Validation tools MUST alert Authors that inclusion of the feature is deprecated when encountered in an EPUB Publication. It is RECOMMENDED that the alert be lower in severity than an error or warning.
> 
> If a feature is marked as superseded, the following hold true:
> 
> - <strike>The superseded feature MAY be removed in a future version of the specification, but there is no definite timeline for removal.</strike>
> 
> - Authors MAY include the superseded feature for compatibility with older versions of the specification.
> 
> - Reading Systems MUST NOT support the superseded feature in content that conforms to the current version of the specification.
> 
> - Validation tools MUST NOT alert Authors about the presence of the superseded feature in an EPUB Publication, as it is valid for backwards compatibility. Validation tools MUST alert Authors if the superseded feature is not conformant to its definition or otherwise breaks a usage requirement.
> 
> <strike>
> A feature that is superseded and marked for removal differs from a superseded feature in the following ways:
> 
> - The feature will be removed in a future version of the specification.
> 
> - Validation tools MUST alert Authors about the presence of superseded features that are marked for removal. It is RECOMMENDED that the alert be given the same severity as deprecated features.
> </strike>

Are there any features we can't slot into one of the above two buckets?

**Comment by mattgarrish** [comment] 2018-04-15 12:50
The one thing I don't know what to make of is this requirement for deprecated features:

>  It is RECOMMENDED that the alert be lower in severity than an error or warning.

Either these should always be a warning or this is where we need to consider stricter validation profiles.

**Comment by dauwhe** [comment] 2018-04-15 23:53
I agree that we should stop predicting the future. Look how well we've done with predicting the demise of the NCX!

**Comment by mattgarrish** [comment] 2018-04-16 11:12
This bullet is also a bit vague:

> Authors MAY include the superseded feature for compatibility with older versions of the specification.

It was intended to cover 2.0 and potentially 3.0, but since we're dropping 3.1 we can probably be more explicit here:

> Authors MAY include the superseded feature for compatibility with EPUB 2.

**Comment by mattgarrish** [comment] 2018-04-16 13:01
Here's a possible reformulation (that we can edit more easily):
https://docs.google.com/document/d/1pT_Osug3yPnLTfaMEUcW4N9-Mk8lUupdG6yb36x4tWc/edit?usp=sharing

**Comment by iherman** [comment] 2018-04-17 13:30
I am not sure if it is of any help, but just as a reference for how W3C uses these terms:

https://www.w3.org/2016/11/obsoleting-rescinding/

the difference is that these terms are used for full specifications and not for individual terms, which is slightly different.

**Comment by mattgarrish** [comment] 2018-05-02 13:56
Closing this issues as new definitions were added in #1029.

**Closed as completed by mattgarrish** 2018-05-02 13:56 UTC
Labels: Spec-EPUB3, EPUB32
