### ISSUE TITLE
Is rendition:align-x-center allowed as a manifest meta?

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#1380] opened 2020-10-28 13:34 UTC
The definition in [§4.3.3.3.2](https://w3c.github.io/epub-specs/epub33/core/#align-x-center) says:

> The `rendition:align-x-center` property specifies that the given spine item should be centered horizontally in the viewport or spread.

This _suggests_ that this property is meaningful on an item reference only. In other words:

```xml
<metadata>
    <meta property="rendition:align-x-center">true</meta>
</metadata>
```

or something similar is not allowed. I think that should be stated explicitly.

**Comment by mattgarrish** [comment] 2020-10-28 17:14
There's always been a question of whether anyone has implemented it. It goes beyond just where to place the spine item and requires the reading system to center the content within the page. See https://www.w3.org/dpub/IG/wiki/NakaTobira_01

We might want to consider deprecating it if it's not actually in use.

**Comment by mattgarrish** [comment] 2020-10-28 17:15
But it's not a global property, as it just doesn't make sense outside the noted use case.

**Comment by shiestyle** [comment] 2020-10-28 22:11
Let me confirm the current status in Japan before deprecated because it was proposed from Japan, I think.

**Comment by iherman** [comment] 2020-10-29 08:15
> But it's not a global property, as it just doesn't make sense outside the noted use case.

I did not dispute that. But this is the only rendition property I found that was defined on a spite element only, and it is worth emphasizing that.

**Comment by toshiakikoike** [comment] 2020-10-30 01:04
At the time of proposing this specification, Japanese publishers had to make trial and error of complicated description methods to realize this function.
After that, I remember that publishers did not strongly request the implementation to RS vendors because it could be realized with many RSs by the following methods.

Sample:
EPUB
https://github.com/toshiakikoike/epub_file/blob/master/mymedia.epub

Markup
https://github.com/toshiakikoike/epub_file/blob/master/mymedia/OEBPS/text/book_0001.xhtml

CSS
https://github.com/toshiakikoike/epub_file/blob/master/mymedia/OEBPS/styles/ebook_style_x.css
html {
  -epub-writing-mode:horizontal-tb;
  -webkit-writing-mode:horizontal-tb;
}

div.chapt {
  width: auto;
  height: 100%;
  margin-right: auto;
  margin-left: auto;
  text-align:left;
  -epub-writing-mode: vertical-rl;
  -webkit-writing-mode: vertical-rl;
}

I have created a sample using rendition: align-x-center in the past.

https://github.com/toshiakikoike/epub-testsuite/tree/master/content/30/epub30-test-0130

I checked the implementation status of some RSs with this file.
I haven't looked at everything, but it's almost unimplemented.


**Implemented**
BinB Reader(by Voyager Japan,Inc. that I belong)
https://r.binb.jp/epm/e1_163698_29102020112202/?cid=Av0ndwJzdy3Dob1C&adr=291209


**Not implemented**
Kindle(confirmed by Previewer 3)
Kinoppy
Rakuten Kobo
Sony Reader
Google PlayBooks

**Comment by shiestyle** [comment] 2020-11-04 14:35
As Koike-san mentioned, 'align-x-center' can be deprecated, I think.

**Comment by llemeurfr** [comment] 2020-11-04 14:39
From the Readium developer community: this is not supported in Readium software. 

Long time ago we've logged the issue [in our Wiki](https://github.com/readium/readium-css/wiki/Internationalization,-pagination-and-user-settings#overarching-issues). Support in EPUB files is so poor that there were conversations about how it was a mistake to have such presentation features in the OPF instead of via CSS expressions. 
This is also expressed in the EPUB spec and in this thread. 
-> In favor of deprecation.

**Comment by iherman** [comment] 2021-02-26 16:19
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-02-26-epub#section3-1) on 2021-02-26

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.1. Is `rendition:align-x-center` allowed as a manifest meta? 

_See github issue [#1380](https://github.com/w3c/epub-specs/issues/1380)._




**Dave Cramer:** this is about `rendition:align-x-center`  
… the intent was that this would be used to center title pages in Japanese books  
… so that everything would be in center of viewport  
… issue here is that this is a bit of metadata that does not make sense as global metadata  
… but the spec seems to allow it  
… should we fix this by prohibiting it as global?  
… there does seem to be some interest in deprecating it entirely  

**Garth Conboy:** we (Google) don't implement it  
… if you had a landscape image in fixed layout, it seems to me that there could be a use case for the global setting  

**Brady Duga:** you said earlier that there have already been other ways to address the use case of Japanese title pages  
… not sure that this is the case  
… i'm currently dealing this an issue report about this right now  
… the experts in Japanese rendering would currently say that there is not real CSS solution to this, but only after a great deal of specific research  

**Matt Garrish:** its not possible for this to be a global property right now  
… because there are no defined values for it currently  

**Dave Cramer:** We do have the datapoint that a careful reader of the spec was unsure that this could be a global property  
… that's some evidence that an editorial note or tweak is needed  

**Matt Garrish:** I have no issue sticking a note in  
… we can't actually have a global property, it's impossible  

**Dave Cramer:** Let's close the issue and have a separate discussion about whether it should be deprecated  
… we're potentially running into not having 2 implementations  
… making this an at-risk feature  

**Ivan Herman:** Minutes are sufficient  

</details>

**Comment by mattgarrish** [comment] 2021-03-09 15:30
Closing this issue per the meeting minutes. Deprecation can be raised separately and/or we'll have to deal with this when it comes time to find implementations.

**Closed as completed by mattgarrish** 2021-03-09 15:30 UTC
Labels: Spec-EPUB3, EPUB33
