### ISSUE TITLE
Processing of navigation documents: ruby, BIDI, character-like images, etc.

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#1793] opened 2021-09-06 08:20 UTC
EPUB3 allows navigation documents to contain many HTML5 elements.  I believe that we can use BIDI-in-HTML, ruby-in-HTML, character-like images, [tate-chuu-yoko](https://www.w3.org/TR/2019/PR-css-writing-modes-3-20191024/#text-combine), and many other text decoration mechanisms are allowed.

However, it appears that many reading systems automatically create user interface constructs from navigation documents.  Since such user interface constructs provided by OS do not support rich text, reading systems generate flat text from each item in navigation documents.  Thus, the use of the rich mechanisms mentioned above will lead to poor results.

If this is the case, shouldn't we explicitly discourage the use of rich constructs in navigation documents?  But I am not sure how BIDI is handled.  Is BIDI-in-HTML in nav docs automatically translated to BIDI-in-Unicode?

[Navigation Document Processing in EPUB Reading Systems 3.3](https://www.w3.org/TR/epub-rs-33/#sec-nav) is silent now.

**Comment by shiestyle** [comment] 2021-09-06 08:50
There are no strong requirements to display rich text for reading system vendors from publishers in Japan.
And nobody needs to restrict for using rich text by specs because there are few trouble on this topic.

**Comment by murata2makoto** [comment] 2021-09-07 02:05
DAISY people in Japan would like to make things clearer.

**Comment by iherman** [comment] 2021-09-07 07:31
@murata2makoto the current [content spec says](https://w3c.github.io/epub-specs/epub33/core/#sec-nav-intro):

> Note that Reading Systems may strip scripting, styling, and HTML formatting as they generate navigational interfaces from information found in the EPUB Navigation Document. If EPUB Creators require such formatting and functionality, then they should also include the EPUB Navigation Document in the spine. 

I would not agree with "explicitly discourage the use of rich constructs in navigation documents": the EPUB Author is warned on what he/she should and could do if a full visual richness is to be used and also that the RS may strip those. 

As for: 

> Is BIDI-in-HTML in nav docs automatically translated to BIDI-in-Unicode?

I do not think this is specified. Though, at first glance, it may make sense to add it to the [bullet items in the RS spec](https://www.w3.org/TR/epub-rs-33/#sec-nav), I would be worried that this is not that simple spec-wise (I do not think the HTML spec includes such a formal mapping, meaning that we would have to specify some sort of micro-syntax ourselves. Also, this may open some flood-gates: why stop at the interpretation of BIDI? What about the interpretation of ruby? Of emphasis or underscore?

My vote would be to leave things as is. This sounds like reflecting the consensus on the [WG Call](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-08-27-epub#section3), see, e.g.: 

> … if we change this RS cannot use native UI elements to present nav
… would have to be a webview
… I don’t think what is being suggested is achievable

**Comment by murata2makoto** [comment] 2021-09-07 13:43
@iherman 

In the case of ruby, "scripting, styling, and HTML formatting" is not good enough.  Consider `<ruby><rb>foo</rb><rt>bar</rt></ruby>`.  Flat text generated from it should be "foo" rather than "foo bar".

**Comment by iherman** [comment] 2021-09-07 13:59
> @iherman
> 
> In the case of ruby, "scripting, styling, and HTML formatting" is not good enough. Consider `<ruby><rb>foo</rb><rt>bar</rt></ruby>`. Flat text generated from it should be "foo" rather than "foo bar".

I understand, but where does this affect my argument? What I said was: authors should not rely on the RS to do these things properly when generating the Table of Content. I hate this is the case, but that is the sad reality. And the current specs makes it clear to authors that this is the case.

I am not sure what change, if any, you propose on the spec.

**Comment by murata2makoto** [comment] 2021-09-08 00:59
@iherman 

> I am not sure what change, if any, you propose on the spec.

We can further say that navigational interfaces created by simply stripping markup might not be readable.

**Comment by mattgarrish** [comment] 2021-09-08 15:23
Is this something we should take up in the accessibility techniques rather than the core specification?

It sounds like a useful advisory for accessibility to avoid ruby markup in the navigation document when it would pose readability issues. Or maybe it's a case for recommending a title attribute with an alternative text string for reading systems that can't handle html tagging rather than forbid the markup?

**Comment by iherman** [comment] 2021-09-08 15:32
> Is this something we should take up in the accessibility techniques rather than the core specification?
> 
> It sounds like a useful advisory for accessibility to avoid ruby markup in the navigation document when it would pose readability issues. Or maybe it's a case for recommending a title attribute with an alternative text string for reading systems that can't handle html tagging rather than forbid the markup?

@mattgarrish the problem is that this is not an accessibility issue only. Ignoring, say, base direction control may completely mess up a title...

But... maybe both are fine. #1805 proposes a minimal change in the core text, and the a11y spec may elaborate on the more accessibility related issues if needed.

**Comment by mattgarrish** [comment] 2021-09-08 17:01
> the problem is that this is not an accessibility issue only

Right, but we're never going to "solve" the problem of being able to express content in html on the one hand but having it pulled into a non-html rendering on the other.

> and the a11y spec may elaborate on the more accessibility related issues if needed

Right, this is also partially a response to the earlier question about having reading systems process aria attributes. The use of title was the intended method to provide an accessible alternative string for a widget, so I think it would be helpful to note its existence and purpose in the techniques.

**Comment by murata2makoto** [comment] 2021-09-09 00:56
Here is an [example EPUB publication](https://1drv.ms/u/s!An5Z79wj5AZBkahc40c2qAbgzKr0UQ?e=h75sLB) containing lots of ruby.  It is a well-known very pedantic detective story.  Thorium simply strips ruby markup and creates "foo bar" rather than "foo" (see my comment above). 

Here is some background information.  Japanese DAISY textbooks have been in DAISY 2.2 but migration to EPUB 3 has started.  We would like to attach ruby to all CJK ideographic characters and control the visibility of ruby depending on user preferences.  What should we do in creating navigation documents?  Half of me thinks that the use of ruby is good for future assistive technology.  The other half thinks that it leads to unreadable results in too many reading systems.

**Comment by iherman** [comment] 2021-09-09 06:51
> > the problem is that this is not an accessibility issue only
> 
> Right, but we're never going to "solve" the problem of being able to express content in html on the one hand but having it pulled into a non-html rendering on the other.

Unfortunately true.

> 
> > and the a11y spec may elaborate on the more accessibility related issues if needed
> 
> Right, this is also partially a response to the earlier question about having reading systems process aria attributes. The use of title was the intended method to provide an accessible alternative string for a widget, so I think it would be helpful to note its existence and purpose in the techniques.

@mattgarrish do you prefer to merge/close #1805 and open a separate one for the A11y document, or add it to #1805. Frankly, I prefer not to touch the A11y spec, I am much less familiar with it...

**Comment by mattgarrish** [comment] 2021-09-09 11:52
> do you prefer to merge/close #1805 and open a separate one for the A11y document, or add it to #1805

I would just leave this issue open when the PR is merged. I'll tag it with an a11y label and we can discuss whether there's anything to be done in the techniques in the task force.

**Comment by iherman** [comment] 2021-09-09 13:37
Ok, I merged #1805, and this issue stays...

**Comment by murata2makoto** [comment] 2021-09-12 05:57
In the last weekly meeting of the technical committee of the Japan DAISY Consortium, we discussed this issue.  EPUB3 textbooks to be used from next year do not have ruby in navigation documents, although some programs automatically introduce such ruby.

It appears that #1805 is the best what we can do now.  But I am curious to see what happens when BIDI-in-HTML appears in navigation documents.

**Closed as completed** 2021-09-17 00:25 UTC
Labels: Spec-EPUB3, EPUB33

**Comment by iherman** [comment] 2021-09-17 05:03
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-09-16-epub#section2) on 2021-09-16

List of resolutions:

- ***[Resolution No. 1](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-09-16-epub#resolution1):  Close issue 1793***

<details><summary><i>View the transcript</i></summary>

### 2. Processing of Navigation Documents 

_See github issue [#1793](https://github.com/w3c/epub-specs/issues/1793)._




**Dave Cramer:** issue is that nav is an HTML document, but also meant to be processed by RS  
… RS may use it and turn it into something unlike HTML, i.e. without markup  

**Murata Makoto:** I find that best practice is to use text only in nav  
… i am curious to know what happens when nav contains bidi?  
… will it be converted to bidi in unicode?  
… from bidi markup  

**Shinya Takami (高見真也):** why does DAISY JP want to restricting rendering of nav?  

**Murata Makoto:** I don't want to restrict  

**Dave Cramer:** maybe just include a note to warn that html markup could break  

**Brady Duga:** we hope that bidi is resolvable via unicode. We haven't gotten very many complaints, so if it breaks, its breaking in very few cases  

**Murata Makoto:** so those who create nav should make sure that their nav can be correctly rendered by major RS  

**Brady Duga:** yes, always advisable. Some of these edge cases can be solved, but we haven't done it because no publisher has raised a strong issue about this  
… and we haven't heard much about ruby in toc  
… but maybe that's because JP publishers are tired of raising this issue  
… but if more publishers complain we will take that into account  
… for ruby we could put the ruby text in parentheses after the base text  

**Shinya Takami (高見真也):** many RS don't use rendering systems for toc, so publishers will not strongly request richly decorated tocs  
… i would leave the spec as it is for epub 3.3  

**Dave Cramer:** i'm getting the sense that murata is okay with the change in language introduced by ivan  

**Murata Makoto:** yes, okay by me  

> **Proposed resolution: Close issue 1793** *(Wendy Reid)*

> *Wendy Reid:* +1

> *Dave Cramer:* +1

> *Toshiaki Koike:* +1

> *Shinya Takami (高見真也):* +1

> *Matthew Chan:* +1

> *Masakazu Kitahara:* +1

> *Murata Makoto:* +1

> *Brady Duga:* +1

> ***Resolution #1: Close issue 1793***

</details>
