### ISSUE TITLE
clarify what is meant by ARIA role superseding epub:type

### ISSUE THREAD

**Issue by rdeltour** [w3c/epub-specs#679] opened 2016-02-23 22:25 UTC
The Content Doc spec [says](http://www.idpf.org/epub/31/spec/epub-contentdocs-20160130.html#sec-html-aria-role-attribute):

> The `role` attribute supersedes  the `epub:type` attribute

with a [definition of "supersedes"](http://www.idpf.org/epub/31/spec/epub-spec-20160130.html#sec-overview-deprecated) saying notably:

> Reading Systems **must not** support the superseded feature in content that conforms to this version of the specification.

Currently it means that RS have to simply ignore the `epub:type` attributes. This is probably too strong, especially for all the terms that are allowed in `epub:type` vocabs but not in the DPUB ARIA vocab.

**Comment by mattgarrish** [comment] 2016-02-23 23:01
The issue is the profiles that have more detailed semantics than ARIA is likely to support, right? If we take that out of the equation, then simply not having every semantic from the SSV was a conscious decision and something I believe we can live with.

I keep wondering if going all-in on ARIA is the best option, or if we should have a supplementary attribute for semantics that are only for processing.

That's effectively what we'd be doing if we loosened the restriction, yet it would only work for xhtml and still require another option for html.

**Comment by TzviyaSiegman** [comment] 2016-02-23 23:06
I think we also need to take a hard look at the SSV to see how/if the terms
are used. In the case of indexing, I think we might want to take another
look before essentially creating an xml vocab again.

**Comment by mattgarrish** [comment] 2016-02-23 23:14
Right, I'm just openly wondering if there are other ways to address the semantics than blunt force hammering of semantics into roles for every case.

The linktype attribute is a good example, and maybe index semantics belong in RDFa? I think we can do better than overload ARIA.

It will mean the profiles aren't fully expressable until we update, but at least they'll be cross-compatible.

**Comment by TzviyaSiegman** [comment] 2016-02-23 23:17
That could work well.

**Comment by iherman** [comment] 2016-02-24 05:32
> On 24 Feb 2016, at 00:14, Matt Garrish notifications@github.com wrote:
> 
> Right, I'm just openly wondering if there are other ways to address the semantics than blunt force hammering of semantics into roles for every case.
> 
> The linktype attribute is a good example, and maybe index semantics belong in RDFa? I think we can do better than overload ARIA.
> 
> We should be careful not to regard RDFa as just a way of adding extra attributes on elements. RDFa is a serialization of RDF, and it should be clear at every usage what the subject, predicate, and object is. That may be tricky and also ugly in some cases: e.g., if we want to make a statement on a particular _HTML element_ then we have to have a URL on that particular element, ie, and extra `@id` or something on that effect.

I am skeptical, I must admit, on the usability of RDFa in this respect.

> It will mean the profiles aren't fully expressable until we update, but at least they'll be cross-compatible.

**Comment by mattgarrish** [comment] 2016-02-24 12:27
Yes, it will take more work, but I don't see any real value accrued to users from the semantics used in indexes, only unnecessary information. The value of the data is far higher for a machine that wants to extract the information contained in the index, or a tool that wants to write and maintain it.

I still see value in an epub-type attribute even if we incorporate important user semantics in ARIA, as another option. It would fill the need of indexes and dictionaries for a machine-processable attribute and separate concerns.

I'm more concerned about giving epub:type life in 3.1 than which specific alternative option we go with.

**Comment by mattgarrish** [comment] 2016-05-03 15:41
Closing as no longer applicable to 3.1

**Closed as completed by mattgarrish** 2016-05-03 15:41 UTC
