### ISSUE TITLE
Value of Deprecated and Superseded

### ISSUE THREAD

**Issue by dauwhe** [w3c/epub-specs#991] opened 2018-01-03 20:59 UTC
EPUB 3.1 makes a [distinction](http://www.idpf.org/epub/31/spec/epub-spec.html#sec-overview-deprecated) between deprecated and superseded features, and has a third category of "superseded and marked for removal". 

The distinctions, however, appear to be stronger in theory than in practice. 

1. **Authoring**. Authors can use superseded or deprecated features. The spec "strongly recommends" that authors not use deprecated features, but as we see below that has little force. 

2.  **Validation**. EPUBCheck must report use of deprecated features, but "It is recommended that the alert be lower in severity than an error or warning." Since EPUBCheck doesn't show such alerts by default, there's no consequence for using deprecated features. 

3. **Reading Systems**. Right now, Reading Systems must support deprecated features, and must not support superseded features. Is that true in real life? The [initial 3.0.2 proposal](https://docs.google.com/document/d/1r2RbLipc5VY3vUp_iuPak3oaNxI5BF9gJ5s-98qsmEY/edit#heading=h.izdc9lnn3tf) included the idea of optional reading system support for various deprecated/superseded/obsoleted/discouraged features, which does not fit into the existing scheme. 

4. **Editing tools**. The spec makes no mention of editing such features (see #936).

5. **Future plans**. Deprecated features will be removed in the future, superseded features may be removed. But our present circumstances are showing us the difficulty of actually removing features. Perhaps we can promise that deprecated features will be removed in the next **major** revision. 

So what value are we getting from these distinctions? Could we get away with a single concept, deprecation, and then use Matt's idea of a "strict" validation mode where deprecated features would result in warnings? More in a  [comment](https://github.com/w3c/publ-epub-revision/issues/988#issuecomment-355042325) to  #988.

**Comment by murata2makoto** [comment] 2018-01-05 06:12
Let me repeat what I wrote as a [comment to your comment on EPUB 3.0.2 proposal](https://docs.google.com/document/d/1r2RbLipc5VY3vUp_iuPak3oaNxI5BF9gJ5s-98qsmEY/edit#heading=h.kmm2am3c6p38).

Standards often have archaic features. Many people dream of abandoning such features and hope to migrate to new features, since the support of such archaic features is a burden to implementations and users. Thus, such people spend a lot of time on careful wording of conformance.

However, such sincere hopes are typically betrayed, since users cannot throw away or convert existing data that contain such archaic features. The ex-chair of ISO/IEC JTC1/SC22 (programming languages) says that few archaic features in programming languages have been thrown away.

Due to my past experiences, I personally think that we should not spend too much time on conformance wording and that we should rather spend our small resources on the development of software for detecting or converting archaic features.   Wording in the EPUB 3.0.2 specification should be simple.  The design document of epubcheck about warnings should be separate, and can be as complicated as required/implemented.

**Comment by therealglazou** [comment] 2018-01-05 08:20
So authors can use superseded features that reading systems must not implement? Seems completely wrong to me, and impossible IRL.

**Comment by dauwhe** [comment] 2018-01-05 13:08
> So authors can use superseded features that reading systems must not implement? Seems completely wrong to me, and impossible IRL.

That's exactly the situation in EPUB 3.0.1. I can (and do) use the NCX, although it is superseded. EPUB 3 Reading systems [MUST ignore](http://www.idpf.org/epub/301/spec/epub-publications.html#ncx-superseded) the NCX, and instead get navigational information from `nav`.

> EPUB 3 Publications may include an NCX (as defined in OPF 2.0.1) for EPUB 2 Reading System forwards compatibility purposes, but EPUB 3 Reading Systems must ignore the NCX.

I guess the larger question is, how can we make EPUB simpler and closer to the web without disrupting existing content and ecosystems? Any ideas are welcome.

**Comment by therealglazou** [comment] 2018-01-05 13:15
> I guess the larger question is, how can we make EPUB simpler and closer to the web without disrupting existing content and ecosystems? Any ideas are welcome.

Add an optional - but recommended - `index.html` html file to the root directory of the package holding

1. a viewable copy of the metadata
2. a ToC with links
3. a reading order with links

**Comment by llemeurfr** [comment] 2018-01-05 14:16
@dauwhe I see the interest of keeping two values, _deprecated_ and _superseded_. Re _Marked as removal_, it does not really make sense anymore, knowing the reset that Web Publications and EPUB 4 represent. 

Re _deprecated_, I would be in favor of changing the wording in the equivalent of http://www.idpf.org/epub/31/spec/epub-spec.html#deprecated, by  a) removing the statement about the feature removed in a future version of the specification (it won't be for backward compatibility reasons in 3.x) and b) stating that reading systems MAY fail to support this feature (this is reality). We talked about epubcheck warnings elsewhere. 

Re _superseded_ you've made your point about its use for NCX in EPUB 3 instances.

**Comment by mattgarrish** [comment] 2018-05-03 12:39
Closing this as a duplicate of #1025 which was addressed in #1029.

**Closed as completed by mattgarrish** 2018-05-03 12:39 UTC
Labels: Spec-EPUB3, EPUB32
